### ISSUE TITLE
Any good app to spoof all device's IDs?

### ISSUE THREAD

**Issue by Maj-ew** [thatskymod/Sky-CotL-Scripts#11]
I think the one you uploaded doesn't spoof any ID but I am not sure of this. Also I don't know what ID Sky application actually checks if it's the same phone but new user. I found one app that says it spoofs but not really sure if it really does and it works but only Canvas, Mod Manager is not being created after cloning. The one that worked for me pretty good is 
 https://www.cloneapp.net but as I say it doesn't create mod Manager so I can't do any mods

**Comment by thatskymod** [comment]
Device ID spoofing, what for? I mean you could certainly edit the device fingerprint with something like _MagiskHide Props Config_ (though, that is for rooted users), but why?

To clone Sky or Canvas multiple times, you really only need to change the **_package name_** using an APK editor of your choice (Apktool M is a good freeware that can do that) and they will install as several copies just fine.

**Comment by Maj-ew** [comment]
Spoof all IDs to prevent from tracking after being banned. But I don't know if they do it in Sky? I mean that it is possible to ban your device (Android phone) by some of few IDs or even IP. That's why I am wondering how to prevent that. Or they don't ban like that in Sky? Do you have any cheater forum or do you have any of your own expiernce in getting banned?

**Comment by thatskymod** [comment]
Yes. An account on the Global server I had played daily from April 2020 and on, was caught in a massive ban wave last month (along with [many others](https://www.reddit.com/r/SkyGame/comments/103bkip/pleaded_for_account_ban_but_tgc_refused_to_unban/)).

I was logged into 3 accounts on the same phone. A main and two alts. Only the main was banned and the others are perfectly fine up to this day. TGC collects device, OS and IP details for analytics, but after a ban all that doesn't matter. A ban is permanent and account wide. Cheats = ban, which is fairly predictable.

To continue playing after a ban, you would have to create a new, empty account. Yes, it's disappointing but you can at least somewhat restore your IAP items (if any) and ask friends to join you again.

For useful groups and socials, check out [Credits & Resources](https://github.com/thatskymod/Sky-CotL-Scripts/tree/main/Canvas#credits--resources).

_* the list is not exhaustive and constantly being updated, so come check from time to time, if interested._

I hope this helps!
