### ISSUE TITLE
AutoWax Didnt Work On Spell

### ISSUE THREAD

**Issue by Lim99fox** [thatskymod/Sky-CotL-Scripts#12]
I updated autowax to the latest version, after I opened the spell window, the spell didn't work, and also spam calls

**Comment by thatskymod** [comment]
Hey, AutoWax doesn't have a spell menu, did you mean libgxost? If so, a few miscellaneous fixes have been introduced in `Canvas > Libs > libgxost-1.0.4_fix.so`, please give them a try! ;)

**Comment by Lim99fox** [comment]
Perfect developer 😍
