### ISSUE TITLE
libgxost 1.0.3

### ISSUE THREAD

**Issue by llAstaroth** [thatskymod/Sky-CotL-Scripts#13]
friend in this new update of the hell mod the spells don't work 😭, fix it please

**Comment by thatskymod** [comment]
Hello, a few miscellaneous fixes have been introduced in `Canvas > Libs > libgxost-1.0.4_fix.so`, please give them a try! ;)

**Comment by llAstaroth** [comment]
hello hello friend thank you very much for fixing libgxost 🙏❤️❤️ , it works perfectly , you are the best mod creator I really appreciate your work friend thank you very much for creating these mod 🥺👏

**Comment by thatskymod** [comment]
Hey!

My only role here is to maintain and distribute mods. Any credit goes to their respective [authors](https://github.com/thatskymod/Sky-CotL-Scripts/tree/main/Canvas#credits--resources).
However, I'm learning entry to mid-level programming and I will get there eventually, so thanks in any case. Have a happy New Year!

_* bonus: libgxost updated again, check out version 1.0.5 for even more fixes!_
