### ISSUE TITLE
I request that the honk spam button be removed on Libgxost. I found the issue of people being banned when using spam. 

### ISSUE THREAD

**Issue by Lim99fox** [thatskymod/Sky-CotL-Scripts#14]
### Suggest a New Mod

Hey! You've found a mod we didn't know of? Perfect! Take a moment to submit and help us improve.

### Software Info

**Name:**

**Type:**

**Supported OS(s), version(s):**

- [ ] **Root required?**

**Author:**

**Source:**

**Additional comment (optional):**

**Comment by thatskymod** [comment]
Sorry no, ask {re}Hell's author to change it - either at [@gxostptr_t](https://t.me/gxostptr_t) (Telegram) or [gxost👀#1001](https://discord.com/users/872763993880682557) (Discord).

I'm no developer on my own yet, my only role here is to upload & share good and trusted mods. Your feedback to the original devs won't be heard here.

Good luck! 🤞

**Comment by Lim99fox** [comment]
Aww hahaha okay, thanks for youre information 😆
