### ISSUE TITLE
hell mod 

### ISSUE THREAD

**Issue by llAstaroth** [thatskymod/Sky-CotL-Scripts#15]
Hello thatskymod Friend, the hell mod does not work with the new update, I hope you can solve it please 🙏❤️🥺

**Comment by thatskymod** [comment]
Done, new version: [./Canvas/Libs/libgxost-1.1.0.so](https://github.com/thatskymod/Sky-CotL-Scripts/blob/main/Canvas/Libs/libgxost-1.1.0.so)

**Comment by thatskymod** [comment]
Hello, is there anything else I can help you with?

**Comment by Ghostedexe** [comment]
Hello,
I used the link you just sent but when I import it to canvas and try to use it , it keeps restarting the game also can I have your discord for easy messaging?

**Comment by thatskymod** [comment]
Good news! {re}Hell has just been updated. Find new version attached down below:
[./Canvas/Libs/libgxost-1.1.1.so](https://github.com/thatskymod/Sky-CotL-Scripts/blob/main/Canvas/Libs/libgxost-1.1.1.so)

**Comment by thatskymod** [comment]
> Hello, I used the link you just sent but when I import it to canvas and try to use it , it keeps restarting the game also can I have your discord for easy messaging?

Marking solved and merging into thread #16
