### ISSUE TITLE
能加个联系方式吗

### ISSUE THREAD

**Issue by 3294817671** [thatskymod/Sky-CotL-Scripts#2]

**Comment by thatskymod** [comment]
Hello, how may I help you / 请问有什么可以帮你？
@3294817671

**Comment by HugeFrog24** [comment]
Hello, is this issue still actual / 这个问题仍然相关吗？
@3294817671

**Comment by thatskymod** [comment]
Hello, is this issue still actual / 这个问题仍然相关吗？
@3294817671
