### ISSUE TITLE
Run doesn't work for warping to winged light

### ISSUE THREAD

**Issue by Staccato01** [thatskymod/Sky-CotL-Scripts#20]
**Description:**
Run doesn't work when trying to warp to winged light. It either crashes, shows a buggy screen and it never shows more than two winged light in the map.

**To Reproduce:**
Steps to reproduce the behavior
1. Go to 'any map'
2. Click on 'Run'
3. Scroll down to 'Winged light and click the warp button'

**Expected behavior:**
The game will crash or most of the time show a buggy screen with a red dot in the middle, seemingly under the map where you can't see the character or move.

**Actual behavior:**
Crash, buggy screen

**Screenshots:**
![Screenshot_20230306-121713_Canvas](https://user-images.githubusercontent.com/127140949/223200772-053bc84c-4fe4-4daf-8162-23741ee05993.jpg)

**Machine (please complete the following information):**
 - Device: Samsung S8
 - OS: Android 10
 - App(s) affected:  Canvas
 - Version: 1.1.4

**Additional context:**
it works sometimes, maybe once or twice of all maps

**Comment by thatskymod** [comment]
Hello!

I am in the same boat (although trying to warp to WL does absolutely nothing for me at all).

I didn't create {re}Hell and so not able to provide direct tech support, however you're encouraged to submit any bug reports or ideas to the original author here, under `#bug-error-reports`: https://discord.gg/fDFU5QWKgh

Let me know if that helps!

**Comment by Staccato01** [comment]
> Hello!
> 
> I am in the same boat (although trying to warp to WL does absolutely nothing for me at all).
> 
> I didn't create {re}Hell and so not able to provide direct tech support, however you're encouraged to submit any bug reports or ideas to the original author here, under `#bug-error-reports`: https://discord.gg/fDFU5QWKgh
> 
> Let me know if that helps!

Thank you! It was fixed today but I'll keep in mind to write any other bugs on the discord. Thanks :D

**Comment by thatskymod** [comment]
The issue has partially been addressed in reHell v1.1.5 and fully remedied in [v1.1.6](https://github.com/thatskymod/Sky-CotL-Scripts/blob/main/Canvas/Libs/libgxost-1.1.6.so), therefore I'd consider this case solved. Thanks for bringing this to attention.
