### ISSUE TITLE
how do you mod pleaaase

### ISSUE THREAD

**Issue by zylosophe** [thatskymod/Sky-CotL-Scripts#21]
Hiii
ok sorry it's not an issue about those scripts but i don't know anywhere else to ask
I want to modify Sky but i have no idea about how, can you tell me how you (y'all?) do it?? I found just one thing to uncompile smali code in java code but it doesn't work yet. Please how the heck do you mod Sky??

**Comment by markyvonne63** [comment]
how can i use libfun please 🥺

**Comment by zylosophe** [comment]
> how can i use libfun please 🥺

is that supposed to help to uncompile sky? no idea what is it

**Comment by thatskymod** [comment]
Yes, decompiling game code is an essential part of our workflow. We then analyze the code for interesting classes or values that are worth tweaking.

Sky is composed of these languages:
- **Java** (for preload routines and such),
- **Lua** (for quick prototyping),
- **C++** (for the main game logic).

Therefore, while it's true that we can extract **_some_** resources by unpacking and baksmaling Dalvik bytecode to their original Java counterpart, unfortunately, at some point, you won't get around studying the game's native **libBootloader.so**.

We use tools like debuggers, GameGuardian, IDA Pro, and Ghidra. You should be familiar with how data is stored in RAM, pointers, offsets, etc.

Newer versions of Sky are shipped without symbols and debug information. That means we have to port symbols from older versions manually, and often work with ARM64 assembly (machine code). Pattern and mask searching is your friend.

There are several approaches you could take depending on your goals and level of experience, including Lua scripting, Canvas Lib, LGL Mod Menu creation, etc.

Finally, you can always draw inspiration from other people's code.

**Comment by zylosophe** [comment]
wow thanks for the big answer!

Seems very complicated, well done to you to being able to mod Sky with that

Gonna see this again when I'll have time to try again, thanksss
