### ISSUE TITLE
Smite Spell & Outfit Restrictions

### ISSUE THREAD

**Issue by PlantNightShade** [thatskymod/Sky-CotL-Scripts#29]
### Technical Support
Hey! You've got a question that is not listed in our FAQ or elsewhere? Ask here and we'll do our best to help.

I was wondering if the new Lib Smite will be getting an update where friends can see outfit or spell (mostly spells) they only see default clothing when I change or my spells are invisible to them

**Comment by thatskymod** [comment]
No, unfortunately it is no longer possible to have modded spells or outfits that others can see. TGC has implemented spell ownership verification in their last update.

Here's a breakdown of the process:
1. Sky operates using two protocols: The Gameroom and the API.
2. When you change your outfit, the Gameroom inquires the API server to verify your ownership of the outfit. If you don't own it, your outfit reverts to the default.
3. Likewise, when a spell is applied, the Gameroom checks with the API to confirm your ownership of the spell, and whether you have recently buffed it. If you have recently buffed one, this action would have subtracted the spell from your inventory.

As a result, only legitimately owned spells and outfits are visible to others, and there is nothing we can do to change this.
