### ISSUE TITLE
I can't use my google acount to register

### ISSUE THREAD

**Issue by Nandadepana** [thatskymod/Sky-CotL-Scripts#30]
When i want to switch to my principal account (is with google) appear this message
![Screenshot_2023-05-16-09-38-56-707_git artdeell skymodloader](https://github.com/thatskymod/Sky-CotL-Scripts/assets/133749198/907e2312-962f-4290-a0b4-9e54ba2cef75)
I want to do cr but i can't

**Comment by thatskymod** [comment]
## Resolved in Canvas 1.4.8

The message saying "no authentication info"  shall now no longer appear as of **Canvas 1.4.8**.

The file is available for download down below:

https://github.com/thatskymod/Sky-CotL-Scripts/blob/eb9d495ddb9e4b4ed05de69dd1d4da32ea1ce39e/Canvas/Canvas.apk

**Note for future readers:**
With the rapid pace at which mods are evolving, it is difficult to keep links on aged discussions up-to-date. If you find that the link is broken, consider searching the repository manually.
