### ISSUE TITLE
no authentication info

### ISSUE THREAD

**Issue by felix-Ggasex** [thatskymod/Sky-CotL-Scripts#34]
**Description:**
 cant log in through email

**To Reproduce:**
Steps to reproduce the behavior
1. open canvas
2. try log in through email
3. not working

**Expected behavior:**
 be able to log in through email

**Actual behavior:**
 not able to log in through email

**Screenshots:**

**Machine (please complete the following information):**
 - Device: 
 - OS: 
 - App(s) affected: 
 - Version: 

**Additional context:**

**Comment by thatskymod** [comment]
## Resolved in Canvas 1.4.8

The message saying "no authentication info"  shall now no longer appear as of **Canvas 1.4.8**.

The file is available for download down below:

https://github.com/thatskymod/Sky-CotL-Scripts/blob/eb9d495ddb9e4b4ed05de69dd1d4da32ea1ce39e/Canvas/Canvas.apk

**Note for future readers:**
With the rapid pace at which mods are evolving, it is difficult to keep links on aged discussions up-to-date. If you find that the link is broken, consider searching the repository manually.
