### ISSUE TITLE
Smite doesn't work on my device

### ISSUE THREAD

**Issue by raralyra** [thatskymod/Sky-CotL-Scripts#35]
**Description:**
When I open canvas that have libsmite on my Samsung tablet it keep kicking/crash me out.i can't open sky in canvas

**Expected behavior:**
I tried clear cache and data but still not working

**Machine (please complete the following information):**
 - Device:Samsung galaxy tab s8 
 - OS: Android 13
 - App(s) affected: canvas,mod manager
 - Version: 1.3.6

**Additional context:**
I tried remove the smite only added the auto wax and it's working.

**Comment by thatskymod** [comment]
Thank you for your request.

It appears you are using an outdated version of Canvas, as indicated by the version number you provided (`1.3.6`).

A newer version of Canvas, released on 23 February 2024, addresses most of the issues you've mentioned, including the crashing problems. It is available at https://github.com/RomanChamelo/Canvas-Open-Source/releases/tag/v1.4.5.

Marking this as outdated/stale.
