### ISSUE TITLE
Libfun and Libhellboy Error

### ISSUE THREAD

**Issue by Lim99fox** [thatskymod/Sky-CotL-Scripts#4]
Error after the sky game is updated

**Comment by thatskymod** [comment]
Hi @Lim99fox,

thanks for reporting. I will take note and update the repository as soon as I know more.

If you really miss the features of Libfun and LibHellboy, you can install previous Sky [0.19.5](tel:0195) ([206971](tel:206971)) from an APK, and profit from the libs for a few more days until TGC enforces the update.

**Comment by Lim99fox** [comment]
I'll do that, thank you so much
