### ISSUE TITLE
Libfun key Telegram Error

### ISSUE THREAD

**Issue by Lim99fox** [thatskymod/Sky-CotL-Scripts#7]
Please help 
![Screenshot_20221208-194818](https://user-images.githubusercontent.com/120006539/206439409-f5b16993-435d-4633-82dc-f564442d82ae.png)

**Comment by thatskymod** [comment]
There's nothing wrong with the commands you entered, but it's said that the author made payware out of libfun and free keys are no longer given, as the output already suggests. He's not being too open about this change (in fact, I can't find him in any groups by his tag - `@littleming`), and the bot response to `/donate` is just a generic placeholder (it tells you to contact him but not at which address). It's all very obscure.

Either way, I'd suggest staying with **libgxost 1.0.0** for now. It's a complete overhaul of hellboy + gxost and about as good as libfun, if not better.
